version: "3" 

services:  
  investment-portfolio:    
    container_name: investment-portfolio
    image: dockerhub.petrmikolas.cz/investmentportfolio:latest   
    user: root
    environment:
     - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped      
    ports:
      - 5600:8080  
      - 5601:8081   
    volumes:     
      - ./appsettings.Production.json:/app/appsettings.Production.json
      - ./DataProtectionKeys:/app/Keys
    network_mode: bridge 